name: surveyscout
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.3.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: SourceSans3
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf
          weight: 400

    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans_7pt_SemiCondensed-Medium.ttf
          weight: 400  # Sesuaikan dengan bobot sebenarnya
        - asset: assets/fonts/NunitoSans_7pt-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans_7pt-ExtraLight.ttf
          weight: 300

  uses-material-design: true

  assets:
    - assets/images/surveyscoutlogo.png
    - assets/images/surveyscout1.png
    - assets/images/google.png
    - assets/images/merekrut.png
    - assets/images/selesai.png
    - assets/images/butuhtinjau.png
    - assets/images/dikerjakan.png
    - assets/images/duaharilalu.png
    - assets/images/pdfexcel.png
    - assets/images/chat.png
    - assets/images/aksi.png
    - assets/images/2bulanlagi.png
    - assets/images/foto1.png
    - assets/images/foto2.png
    - assets/images/foto3.png
    - assets/images/taskantor.png
    - assets/images/taskantorjam.png
    - assets/images/titik3.png
    - assets/images/chat.png
    - assets/images/peringatan.png
    - assets/images/gradienmerah.png
    - assets/images/butuhtinjau2.png
    - assets/images/selesai2.png
    - assets/images/download.png
    - assets/images/chat3.png
    - assets/images/saya.png
    - assets/images/proyek.png